### ISSUE TITLE
relion_autopicking wizard

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-relion#23] opened 2019-01-15 17:51 UTC
Not the Log picker!
After running once in optimizae mode and clicking in the wizard I get this:
`Labels MDL_MICROGRAPH or MDL_IMAGE not found in metadata Tmp/4290.outputMicrographsSubset/micrographs.xmd`
@delarosatrevin is it because of pending xmipp PRs?

**Comment by delarosatrevin** [comment] 2019-02-20 16:25
Is this still happening?

**Comment by azazellochg** [comment] 2019-02-23 16:38
I'm pulling latest xmipp now, will check again

**Comment by delarosatrevin** [comment] 2019-02-23 16:45
Don't worry, I think I know where the issue is and it is not solved with
latest version of Xmipp.

**Comment by delarosatrevin** [comment] 2019-03-13 14:30
Fixed in ca39a5b91af1a22b

**Closed by delarosatrevin** 2019-03-13 14:30 UTC
