### ISSUE TITLE
relion refine 3.1 (devel) does not write star file.

### ISSUE THREAD

**Issue by pconesa** [scipion-em/scipion-em-relion#197] opened 2020-07-17 07:58 UTC
**Describe the bug**
I'm trying to run a new (not from another refine) relion refine and is failing at the convertInputStep.

**To Reproduce**
running relion refine. maybe the input data affects
 

**Desktop (please complete the following information):**
 - Scipion version: [e.g. 3.0]
 - Relion plugin version branch devel (installed now)

File 'Runs/025153_ProtRelionRefine3D/logs/run.stdout' doesn't exist00001:   RUNNING PROTOCOL -----------------
00002:        HostName: galileo.cnb.csic.es
00003:             PID: 74573
00004:      pyworkflow: 3.0.0
00005:      currentDir: /data/rmelero/covid-19_3207
00006:      workingDir: Runs/025153_ProtRelionRefine3D
00007:         runMode: Restart
00008:             MPI: 9
00009:         threads: 8
00010:   000/??? sec ~~(,_,">                                                          [oo]00011:   
00012:      6/   6 sec ............................................................~~(,_,">
00013:   ** Running command: relion_image_handler --i Runs/010357_ProtRelionCreateMask3D/extra/mask.mrc --o Runs/025153_ProtRelionRefine3D/tmp/mask.mrc --angpix 1.04700 --rescale_angpix 1.04700 --new_box 400 --threshold_above 1 --threshold_below 0
00014:    Starting at step: 1
00015:    Running steps 
00016:   STARTED: convertInputStep, step 1
00017:     2020-07-17 11:49:22.742215
00018:   Converting set from 'Runs/016125_ProtRelionBayesianPolishing/particles.sqlite' into 'Runs/025153_ProtRelionRefine3D/input_particles.star'
00019:   convertBinaryFiles: creating soft links.
00020:      Root: Runs/025153_ProtRelionRefine3D/extra/input -> Runs/016125_ProtRelionBayesianPolishing/extra
00021:   Traceback (most recent call last):
00022:     File "/usr/local/scipion3/.scipion3env/lib/python3.6/site-packages/pyworkflow/protocol/protocol.py", line 188, in run
00023:       self._run()
00024:     File "/usr/local/scipion3/.scipion3env/lib/python3.6/site-packages/pyworkflow/protocol/protocol.py", line 239, in _run
00025:       resultFiles = self._runFunc()
00026:     File "/usr/local/scipion3/.scipion3env/lib/python3.6/site-packages/pyworkflow/protocol/protocol.py", line 235, in _runFunc
00027:       return self._func(*self._args)
00028:     File "/usr/local/scipion3/plugin3/scipion-em-relion/relion/protocols/protocol_base.py", line 797, in convertInputStep
00029:       mdOptics.writeStar(imgStar, tableName='optics')
00030:     File "/usr/local/scipion3/.scipion3env/lib/python3.6/site-packages/emtable/metadata.py", line 358, in writeStar
00031:       writer.writeTableName(tableName)
00032:     File "/usr/local/scipion3/.scipion3env/lib/python3.6/site-packages/emtable/metadata.py", line 243, in writeTableName
00033:       self._file.write("\ndata_%s\n\n" % (tableName or ''))
00034:   AttributeError: 'str' object has no attribute 'write'
00035:   Protocol failed: 'str' object has no attribute 'write'
00036:   FAILED: convertInputStep, step 1
00037:     2020-07-17 11:50:17.270507
00038:   *** Last status is failed 
00039:   ------------------- PROTOCOL FAILED (DONE 1/3)

**Comment by azazellochg** [comment] 2020-07-17 08:26
relion version?
Runs/016125_ProtRelionBayesianPolishing was done in which relion version?

**Comment by azazellochg** [comment] 2020-07-19 08:58
Bug confirmed, there's a problem with converting

**Comment by delarosatrevin** [comment] 2020-07-19 09:13
I'll take a look at this tomorrow.

**Comment by azazellochg** [comment] 2020-07-19 14:28
@delarosatrevin I have a different error: 00040:   ERROR  The reference box size is 256 px, but the box size of the first optics group of the data is 182 px! I cant seem to find where does it get wrong image size

**Comment by azazellochg** [comment] 2020-07-25 17:07
I have fixed my error. @pconesa could you tell Runs/016125_ProtRelionBayesianPolishing was done in which relion version? or how did you get it?

**Comment by pconesa** [comment] 2020-07-25 21:54
Very likely scipion2, relion3.0

**Comment by azazellochg** [comment] 2020-07-25 21:56
Thanks, I'll try my best to reproduce it

**Comment by pconesa** [comment] 2020-07-27 13:03
Extract of the log--> Doicletian -->Scipion2 relion3.0.

^[[32mRUNNING PROTOCOL -----------------^[[0m
     HostName: scipioncovid19
          PID: 47761
      Scipion: v2.0 (2019-04-23) Diocletian
   currentDir: /vol-sw-project/covid-19_3207
   workingDir: Runs/016125_ProtRelionBayesianPolishing
      runMode: Restart
          MPI: 1
      threads: 30
 Starting at step: 1
 Running steps
^[[35mSTARTED^[[0m: convertInputStep, step 1
  2020-05-03 09:30:02.168826
Converting set from 'Runs/016067_ProtRelionCtfRefinement/particles.sqlite' into 'Runs/016125_ProtRelionBayesianPolishing/input_particles.star'
convertBinaryFiles: creating soft links.
   Root: Runs/016125_ProtRelionBayesianPolishing/input/particles/input -> Runs/014381_ProtRelionExtractParticles/extra
^[[35mFINISHED^[[0m: convertInputStep, step 1
  2020-05-03 09:32:03.372556
^[[35mSTARTED^[[0m: trainOrPolishStep, step 2
  2020-05-03 09:32:04.009700
@

**Comment by azazellochg** [comment] 2020-08-15 19:10
hm, I ran polishing in 3.0 (scipion3) and then launched ref3d in 3.1 (scipion3). No errors in conversion..

**Comment by delarosatrevin** [comment] 2020-08-27 11:55
@pconesa Do you have seen this issue pop-up again? We have recently run many refine 3d (tutorial and real data sets) and it is working. If not, we should close this and open a more specific issue.

**Comment by azazellochg** [comment] 2020-08-27 11:59
@delarosatrevin the isuue is going from scipion 2 + relion30 to scipion3 + relion31. I don't think you ran those :)

**Comment by delarosatrevin** [comment] 2020-08-27 12:23
No, you are not...I haven't run this sequence, but I might try as well. @pconesa Could you try to provide more context the the origin of the input set of particles?

**Comment by azazellochg** [comment] 2020-08-27 12:27
@delarosatrevin As far as I understood @pconesa ran polishing in scipion2 then opened the project in scipion3 and tried to run 3d refine.

**Comment by pconesa** [comment] 2020-08-27 14:36
@azazellochg is right. There was a project created mostly with scipion2 (almost completed). Multibody was failing in scipion 2 so we tried to run it under scipion3 code. 

I think @azazellochg  suggested me to feed multibody with refinement also run with scipion3 code. So that is what I did and reported here.

The feeder for the refinement was a existing bayesian polishing (scipion2 + relion 3.0)

**Comment by vabrishami** [comment] 2020-10-09 09:25
@azazellochg @pconesa @delarosatrevin I have the same issue. So here is a summary:

I did before localized reconstruction in Scipion 2.0 + Relion 3.0 (from defining sub-particles to sub-particles classification and refinement). Now, I wanted just to repeat the refinement part since a user reported a bug related. But at the very beginning of refinement, I have this error:

/envs/.scipion3env/lib/python3.8/site-packages/emtable/metadata.py", line 243, in writeTableName
00034:       self._file.write("\ndata_%s\n\n" % (tableName or ''))
00035:   AttributeError: 'str' object has no attribute 'write'
00036:   Protocol failed: 'str' object has no attribute 'write'

So it would be great if we have a fix for that soon.

**Comment by delarosatrevin** [comment] 2020-10-09 09:29
Thanks @vabrishami. I will try to take a look at this later today.

**Comment by azazellochg** [comment] 2020-10-25 18:01
I ran relion30 refine (outside scipion) and then imported particles and ran relion31 - refine 3d (scipion3). This way it works. Will have to go back to scipion2 + relion30 to check further.

**Comment by azazellochg** [comment] 2020-10-25 18:27
Now I ran ref3d in scipion2+relion30 and then used as input for scipion3+relion31. It worked as well. I don't think I will be able to reproduce this unless someone sends a full workflow or gives a remote access to the project.

**Comment by azazellochg** [comment] 2020-11-22 19:50
I believe localrec-related issue was fixed. @pconesa do you still have this issue? If so, please reopen and send me input sqlite files.

**Closed by azazellochg** 2020-11-22 19:50 UTC
Labels: bug, help wanted, relion3.1

**Comment by pconesa** [comment] 2020-11-23 06:07
Thanks, I'll reopen if happens again
